name: CodeMender PR Scan

on:
  pull_request:

jobs:
  compliance-check:
    name: Mandatory CodeMender Scan
    # Skips execution entirely if the pull request is a draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout the target repository's code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ github.repository_owner }}/${{ inputs.repo_name }}
      #     token: ${{ secrets.ORG_READ_TOKEN }} # Needs read/write access to the target repo
      #     fetch-depth: 0
      #     path: ${{ inputs.repo_name }}

      - name: Run linting or security scanner
        run: |
          echo "Running mandatory compliance validations for repo ${{ github.event.action }}..."
          echo "Submitted by ${{ github.actor }}"
          # Insert your test scripts, linting tools, or security scans here
          echo "PR for: \n\n ${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
          echo "Repo Full Name: \n\n ${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_STEP_SUMMARY
          echo "Title: \n\n ${{ github.event.pull_request.title }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Get Changed Files via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "### Listing changed files..." >> $GITHUB_STEP_SUMMARY
          # 1. Fetch the files from the API and read them into a Bash array line-by-line
          mapfile -t CHANGED_FILES < <(gh api repos/${{ github.repository }}/pulls/${{ github.event.number }}/files --jq '.[].filename')

          # 2. Iterate through the list/array
          for file in "${CHANGED_FILES[@]}"; do
            echo "Processing modified file: $file"
          done

      # Needs to be updated before use
      # - name: Checkout Code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ github.event.pull_request.head.repo.full_name }}
      #     token: ${{ secrets.ORG_READ_TOKEN }} # Needs read/write access to the target repo
      #     fetch-depth: 0
      #     path: ${{ github.event.pull_request.head.repo.name }}
    
      
