name: test
on:
  workflow_dispatch:

jobs:
  dispatch-task:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Authenticate to Google Cloud securely
      - name: Find where the dir is
        run: |
          echo "$(pwd)"
          echo "$(ls)"
