name: test
on:
  workflow_dispatch:

jobs:
  dispatch-task:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Find where the dir is
        run: |
          pwd
          ls -la
